services:
  #Readarr
  readarr:
    container_name: readarr
    image: ghcr.io/hotio/readarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Asia/Kolkata
    volumes:
      - ./APPDATA/readarr/config:/config
      - ${MEDIA_PATH}:/media
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      prowlarr:
        condition: service_started
    network_mode: "service:wireguard-client"
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 7s
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
  #Bazarr
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ./APPDATA/bazarr/:/config
      - ${MEDIA_PATH}:/media
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    network_mode: "service:wireguard-client"
    depends_on:
      prowlarr:
        condition: service_started
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 7s
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

  #Lidarr
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ./APPDATA/lidarr/config:/config
      - ${MEDIA_PATH}:/media
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    network_mode: "service:wireguard-client"
    depends_on:
      prowlarr:
        condition: service_started
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 9s
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

  #Sonarr
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - TZ=Asia/Kolkata
    volumes:
      - ./APPDATA/sonarr/config:/config
      - ${MEDIA_PATH}:/media
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    network_mode: "service:wireguard-client"
    depends_on:
      prowlarr:
        condition: service_started
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

  #Radarr
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - TZ=Asia/Kolkata
    volumes:
      - ./APPDATA/radarr:/config
      - ${MEDIA_PATH}:/media
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    network_mode: "service:wireguard-client"
    depends_on:
      prowlarr:
        condition: service_started
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 11s
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

        # Whisparr
  whisparr:
    container_name: whisparr
    image: ghcr.io/hotio/whisparr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Asia/Kolkata
    volumes:
      - ./APPDATA/whisparr:/config
      - ${MEDIA_PATH}:/media
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    network_mode: "service:wireguard-client"
    depends_on:
      prowlarr:
        condition: service_started
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 11s
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"