services:


        #Bazarr
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ${APPDATA_PATH}/bazarr/:/config
      - ${MEDIA_PATH}:/media
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    network_mode: "service:gluetun"
    depends_on:
      prowlarr:
        condition: service_started
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 7s
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

  #Lidarr
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ${APPDATA_PATH}/lidarr/config:/config
      - ${MEDIA_PATH}:/media
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    network_mode: "service:gluetun"
    depends_on:
      prowlarr:
        condition: service_started
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 9s
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

  #Sonarr
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - TZ=Asia/Kolkata
    volumes:
      - ${APPDATA_PATH}/sonarr/config:/config
      - ${MEDIA_PATH}:/media
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    network_mode: "service:gluetun"
    depends_on:
      prowlarr:
        condition: service_started
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

  #Radarr
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - TZ=Asia/Kolkata
    volumes:
      - ${APPDATA_PATH}/radarr:/config
      - ${MEDIA_PATH}:/media
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    network_mode: "service:gluetun"
    depends_on:
      prowlarr:
        condition: service_started
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 11s
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
