services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Remove the following line if you don't need user sign in
      - ./users.yml:/data/users.yml
    ports:
      - ${DOZZLE_PORT}:8080
    environment:
      DOZZLE_NO_ANALYTICS: true
      # Remove the following line if you don't need user sign in
      # DOZZLE_AUTH_PROVIDER: simple
    networks:
      home-server:
        ipv4_address: 50.0.0.78
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"