services:
  #Deluge
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ${APPDATA_PATH}/nzbget/config:/config
      - ${MEDIA_PATH}/downloads:/media/downloads #optional
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 15s

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      #- TRANSMISSION_WEB_HOME= #optional
      - USER=${USERNAME}
      - PASS=${PASSWORD}
      #- WHITELIST= #optional
      #- PEERPORT= #optional
      #- HOST_WHITELIST= #optional
    volumes:
      - ${APPDATA_PATH}/transmission/config:/config
      - ${MEDIA_PATH}/downloads:/media/downloads
      - ${MEDIA_PATH}/watch:/media/watch
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 15s

  #NZBGet
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ${APPDATA_PATH}/nzbget/config:/config
      - ${MEDIA_PATH}/downloads:/media/downloads #optional
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 25s
  #Prowlarr
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - TZ=Asia/Kolkata
    volumes:
      - ${APPDATA_PATH}/prowlarr/config:/config
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Asia/Kolkata
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: unless-stopped
