services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    networks:
      home-server:
        ipv4_address: 50.0.0.100
    volumes:
      - ../APPDATA/nextcloud/config:/config
      - ${MEDIA_PATH}/nextcloud:/data
    ports:
      - 1234:443
    restart: unless-stopped

  samba:
    image: dperson/samba
    container_name: samba
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    networks:
      home-server:
        ipv4_address: 50.0.0.110

    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: false
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ${MEDIA_PATH}:/mnt:z
    command: '-s "Shared Media Volume;/mnt;yes;no;no;${USERNAME}" -u "${USERNAME};${PASSWORD}" -p'
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
