services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      # Root directory
      - ${APPDATA_PATH}/filebrowser/config/filebrowser.db:/database/database.db
      - ${APPDATA_PATH}/filebrowser/config/settings.json:/settings.json
      - ${MEDIA_PATH}:/srv/users/esh/media:rw
      - ${APPDATA_PATH}:/srv/users/esh/appdata:rw

      # # Other directories you want to mount
      # # For example
      # # Your server home directory
      # - $HOME:/srv/users/esh/home:rw
      # # Volumes from other apps (must declared in the volumes section)
      # - jellyfin-media:/srv/users/esh/media:rw
    ports:
      - ${FILEBROWSER_PORT}:80
    security_opt:
      - no-new-privileges:true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      home-server:
        ipv4_address: 50.0.0.5
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 50s
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

  it-tools:
    image: corentinth/it-tools:latest
    container_name: it-tools
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      home-server:
        ipv4_address: 50.0.0.6
    restart: unless-stopped
    ports:
      - "${IT_TOOLS_PORT}:80"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

  stirling-pdf:
    image: frooodle/s-pdf:latest
    container_name: stirling-pdf
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      home-server:
        ipv4_address: 50.0.0.7
    ports:
      - "${STIRLING_PDF_PORT}:8080"
    volumes:
      - ${APPDATA_PATH}/stirling-pdf/training-data:/usr/share/tessdata #Required for extra OCR languages
      - ${APPDATA_PATH}/stirling-pdf/configs:/configs
    #      - ./customFiles:/customFiles/
    #      - ./logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
